---
id: about-boot2docker-format-me
base_name: boot2docker-format-me
tags:
- linux
presentation_date: 2018/01/28
version: 2018.01.28
licenses: []
slideshare_id: boot2docker-formatme
speaker_deck_id: boot2docker-false-format-me-falsehua
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
